# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               MAT-doc
tagline:             'Mounting Assistive Technology Documentation'
description:         'The Mounting Assistive Technology Documentation (MAT-DOC) helps those involved with providing assistive technology to ensure it can be used effectively in a range of environments and contexts to meet the lifestyle needs of the user.'
url:                 http://mat-doc.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Paul Hewett
  url:               https://twitter.com/paulhewtweet
  email:             phewett@acecentre.org.uk

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
